### ISSUE TITLE
Property Values

### ISSUE THREAD

**Issue by SergioFaya** [Arquisoft/InciDashboard_i2b#3]
Some agents, like sensors, will continually submit incidents with some property values. The dashboard will
be configured to know which values are allowed and how to classify the property values. 

By using Kafka those property values will be updated in the system so we will need a class and a sort of collection, maybe a map to store them.

**Comment by alejgh** [comment]
Incidents are already filtered by the InciManager, so I don't know if we need to filter them again in the Dashboard. This is not a priority right now.
